from enum import Enum


class WorkflowState(str, Enum):
    IDLE = "IDLE"
    PLANNING = "PLANNING"
    WAITING_FOR_RESPONSE = "WAITING_FOR_RESPONSE"
    RESPONSE_RECEIVED = "RESPONSE_RECEIVED"
    STORED = "STORED"
    READY_FOR_WORKER = "READY_FOR_WORKER"
    IMPLEMENTING = "IMPLEMENTING"
    WAITING_FOR_REPORT = "WAITING_FOR_REPORT"
    REVIEWING = "REVIEWING"
    RETRYING = "RETRYING"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    ERROR = "ERROR"